import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { Invoice } from "@/lib/models/invoice";
import { Business } from "@/lib/models/business";
import { getAuthBusinessId } from "@/lib/api-auth";
import nodemailer from "nodemailer";
import { jsPDF } from "jspdf";

const transporter = nodemailer.createTransport({
  host: process.env.BREVO_SMTP_HOST,
  port: parseInt(process.env.BREVO_SMTP_PORT || "587"),
  auth: {
    user: process.env.BREVO_SMTP_USER,
    pass: process.env.BREVO_SMTP_PASS,
  },
});

function formatCurrency(n: number) {
  return `₹${n.toLocaleString("en-IN")}`;
}

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { businessId, error } = await getAuthBusinessId();
  if (error) return error;

  try {
    await connectDB();
    const { id } = await params;

    const invoice = await Invoice.findOne({ _id: id, businessId }).lean();
    if (!invoice) {
      return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
    }

    if (!invoice.customerEmail) {
      return NextResponse.json({ error: "No email on this invoice" }, { status: 400 });
    }

    const business = await Business.findById(businessId).lean();
    if (!business) {
      return NextResponse.json({ error: "Business not found" }, { status: 404 });
    }

    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pw = doc.internal.pageSize.getWidth();
    const ml = 20;
    const cw = pw - ml - ml;
    let y = 20;

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE", pw / 2, y, { align: "center" });
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(invoice.invoiceNumber, pw / 2, y, { align: "center" });
    y += 5;
    doc.text(
      new Date(invoice.createdAt).toLocaleDateString("en-IN", {
        day: "numeric",
        month: "long",
        year: "numeric",
      }),
      pw / 2,
      y,
      { align: "center" }
    );
    y += 12;

    doc.setFontSize(11);
    doc.text(`Customer: ${invoice.customerName}`, ml, y);
    y += 6;
    if (invoice.customerPhone) {
      doc.text(`Phone: ${invoice.customerPhone}`, ml, y);
      y += 6;
    }
    if (invoice.customerEmail) {
      doc.text(`Email: ${invoice.customerEmail}`, ml, y);
      y += 6;
    }
    y += 4;

    if (invoice.items?.length > 0) {
      doc.setDrawColor(200);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text("Item", ml, y);
      doc.text("Qty", 120, y);
      doc.text("Rate", 150, y);
      doc.text("Amount", 175, y, { align: "right" });
      y += 5;
      doc.line(ml, y, pw - ml, y);
      y += 3;
      doc.setFont("helvetica", "normal");

      for (const item of invoice.items) {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.text(item.name, ml, y);
        doc.text(String(item.quantity), 120, y);
        doc.text(formatCurrency(item.price), 150, y);
        doc.text(formatCurrency(item.total), 175, y, { align: "right" });
        y += 6;
      }
      y += 3;
    }

    if (invoice.services?.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.text("Services", ml, y);
      y += 5;
      doc.line(ml, y, pw - ml, y);
      y += 3;
      doc.setFont("helvetica", "normal");
      for (const s of invoice.services) {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.text(s.name, ml, y);
        doc.text(formatCurrency(s.price), 175, y, { align: "right" });
        y += 6;
      }
      y += 3;
    }

    doc.line(ml, y, pw - ml, y);
    y += 5;

    const totals: { label: string; value: number }[] = [
      { label: "Subtotal", value: invoice.subtotal },
    ];
    if (invoice.labourCharges)
      totals.push({ label: "Labour Charges", value: invoice.labourCharges });
    if (invoice.discount)
      totals.push({ label: "Discount", value: -invoice.discount });

    for (const t of totals) {
      doc.setFont("helvetica", "normal");
      doc.text(t.label, 130, y);
      doc.text(formatCurrency(Math.abs(t.value)), 175, y, { align: "right" });
      y += 6;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Total:", 130, y);
    doc.text(formatCurrency(invoice.total), 175, y, { align: "right" });
    y += 10;

    if (invoice.notes) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(invoice.notes, ml, y);
    }

    doc.setFontSize(8);
    doc.text(`Generated by ${business.name}`, pw / 2, 290, { align: "center" });

    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

    await transporter.sendMail({
      from: process.env.EMAIL_FROM || `"${business.name}" <${process.env.BREVO_SMTP_USER}>`,
      to: invoice.customerEmail,
      subject: `Invoice ${invoice.invoiceNumber} from ${business.name}`,
      html: `
        <div style="font-family: system-ui, sans-serif; max-width: 480px; margin: 0 auto; padding: 24px;">
          <h1 style="font-size: 24px; margin-bottom: 8px;">${business.name}</h1>
          <p style="color: #666; margin-bottom: 24px;">Invoice ${invoice.invoiceNumber}</p>
          <p>Hi ${invoice.customerName},</p>
          <p>Please find your invoice attached.</p>
          <p style="font-size: 28px; font-weight: bold; margin: 24px 0;">${formatCurrency(invoice.total)}</p>
          <p style="color: #999; font-size: 14px;">Thank you for your business!</p>
        </div>
      `,
      attachments: [
        {
          filename: `Invoice_${invoice.invoiceNumber}.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("Send email error:", err);
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }
}
