"use client"

import { useState, useEffect } from "react"
import { useParams } from "next/navigation"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { toast } from "sonner"
import {
  ArrowLeft,
  Download,
  MessageSquare,
  Loader2,
  FileText,
  CheckCircle2,
  Send,
  XCircle,
  Mail,
} from "lucide-react"
import { jsPDF } from "jspdf"

interface InvoiceItem {
  name: string
  quantity: number
  price: number
  total: number
}

interface InvoiceService {
  name: string
  price: number
}

interface Invoice {
  _id: string
  invoiceNumber: string
  customerName: string
  customerPhone: string
  customerEmail: string
  items: InvoiceItem[]
  services: InvoiceService[]
  subtotal: number
  tax: number
  discount: number
  labourCharges: number
  total: number
  status: string
  source: string
  rawTranscript: string
  notes: string
  createdAt: string
}

export default function InvoiceDetailPage() {
  const params = useParams()
  const [invoice, setInvoice] = useState<Invoice | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchInvoice()
  }, [])

  async function fetchInvoice() {
    try {
      const res = await fetch(`/api/invoices/${params.id}`)
      if (!res.ok) throw new Error("Not found")
      const data = await res.json()
      setInvoice(data.invoice)
    } catch (err) {
      console.error("Failed to fetch invoice:", err)
    } finally {
      setLoading(false)
    }
  }

  async function updateStatus(status: string) {
    try {
      const res = await fetch(`/api/invoices/${params.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      })
      if (!res.ok) throw new Error("Failed to update")
      toast.success(`Invoice marked as ${status}`)
      fetchInvoice()
    } catch {
      toast.error("Failed to update invoice")
    }
  }

  async function handleSendEmail() {
    if (!invoice || !invoice.customerEmail) {
      toast.error("No email on this invoice")
      return
    }
    try {
      const res = await fetch(`/api/invoices/${invoice._id}/send`, {
        method: "POST",
      })
      if (!res.ok) {
        const err = await res.json()
        throw new Error(err.error || "Failed to send")
      }
      toast.success("Invoice sent to " + invoice.customerEmail)
    } catch (err) {
      toast.error((err as Error).message || "Failed to send email")
    }
  }

  async function handleWhatsApp() {
    if (!invoice) return

    const message = [
      `Invoice: ${invoice.invoiceNumber}`,
      `Customer: ${invoice.customerName}`,
      "",
      ...invoice.items.map((i) => `${i.name} x${i.quantity} = Rs.${i.total}`),
      ...invoice.services.map((s) => `${s.name} = Rs.${s.price}`),
      invoice.labourCharges ? `Labour: Rs.${invoice.labourCharges}` : "",
      invoice.discount ? `Discount: -Rs.${invoice.discount}` : "",
      "",
      `Total: Rs.${invoice.total}`,
      invoice.notes ? `\nNotes: ${invoice.notes}` : "",
      "",
      "Generated by BolKeBill™",
    ]
      .filter(Boolean)
      .join("\n")

    try {
      const doc = new jsPDF({ unit: "mm", format: "a4" })
      const pageWidth = doc.internal.pageSize.getWidth()
      let y = 20

      doc.setFontSize(22)
      doc.text("INVOICE", pageWidth / 2, y, { align: "center" })
      y += 8
      doc.setFontSize(10)
      doc.text(invoice.invoiceNumber, pageWidth / 2, y, { align: "center" })
      y += 5
      doc.text(
        new Date(invoice.createdAt).toLocaleDateString("en-IN", {
          day: "numeric",
          month: "long",
          year: "numeric",
        }),
        pageWidth / 2,
        y,
        { align: "center" },
      )
      y += 10

      doc.setFontSize(11)
      doc.text(
        `Customer: ${invoice.customerName}${invoice.customerPhone ? ` (${invoice.customerPhone})` : ""}`,
        20,
        y,
      )
      y += 8

      if (invoice.items.length > 0) {
        doc.setDrawColor(200)
        doc.setFontSize(10)
        doc.setFont("helvetica", "bold")
        doc.text("Item", 20, y)
        doc.text("Qty", 120, y)
        doc.text("Rate", 150, y)
        doc.text("Amount", 175, y, { align: "right" })
        y += 5
        doc.line(20, y, pageWidth - 20, y)
        y += 3
        doc.setFont("helvetica", "normal")

        for (const item of invoice.items) {
          if (y > 275) {
            doc.addPage()
            y = 20
          }
          doc.text(item.name, 20, y)
          doc.text(String(item.quantity), 120, y)
          doc.text(`Rs.${item.price}`, 150, y)
          doc.text(`Rs.${item.total}`, 175, y, { align: "right" })
          y += 6
        }
        y += 3
      }

      if (invoice.services.length > 0) {
        doc.setFont("helvetica", "bold")
        doc.text("Services", 20, y)
        y += 5
        doc.line(20, y, pageWidth - 20, y)
        y += 3
        doc.setFont("helvetica", "normal")

        for (const s of invoice.services) {
          if (y > 275) {
            doc.addPage()
            y = 20
          }
          doc.text(s.name, 20, y)
          doc.text(`Rs.${s.price}`, 175, y, { align: "right" })
          y += 6
        }
        y += 3
      }

      doc.line(20, y, pageWidth - 20, y)
      y += 5

      const totals: { label: string; value: number }[] = [
        { label: "Subtotal", value: invoice.subtotal },
      ]
      if (invoice.labourCharges)
        totals.push({ label: "Labour Charges", value: invoice.labourCharges })
      if (invoice.discount)
        totals.push({ label: "Discount", value: -invoice.discount })

      for (const t of totals) {
        doc.setFont("helvetica", "normal")
        doc.text(t.label, 130, y)
        doc.text(`Rs.${Math.abs(t.value)}`, 175, y, { align: "right" })
        y += 6
      }

      doc.setFont("helvetica", "bold")
      doc.setFontSize(14)
      doc.text("Total:", 130, y)
      doc.text(`Rs.${invoice.total}`, 175, y, { align: "right" })
      y += 10

      if (invoice.notes) {
        doc.setFont("helvetica", "normal")
        doc.setFontSize(10)
        doc.text(invoice.notes, 20, y)
        y += 6
      }

      doc.setFontSize(8)
      doc.text("Generated by BolKeBill™", pageWidth / 2, 290, {
        align: "center",
      })

      const pdfBlob = doc.output("blob")
      const pdfFile = new File(
        [pdfBlob],
        `Invoice_${invoice.invoiceNumber}.pdf`,
        {
          type: "application/pdf",
        },
      )

      const shareData: ShareData = {
        files: [pdfFile],
        text: message,
        title: `Invoice ${invoice.invoiceNumber}`,
      }

      if (navigator.canShare && navigator.canShare(shareData)) {
        await navigator.share(shareData)
      } else {
        const url = `https://wa.me/${invoice.customerPhone || "91"}?text=${encodeURIComponent(message)}`
        window.open(url, "_blank")
      }
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        const url = `https://wa.me/${invoice.customerPhone || "91"}?text=${encodeURIComponent(message)}`
        window.open(url, "_blank")
      }
    }
  }

  function handleDownload() {
    if (!invoice) return
    const printWindow = window.open("", "_blank")
    if (!printWindow) return

    const itemsRows = invoice.items
      .map(
        (i) =>
          `<tr><td>${i.name}</td><td>${i.quantity}</td><td>₹${i.price}</td><td>₹${i.total}</td></tr>`,
      )
      .join("")

    const servicesRows = invoice.services
      .map((s) => `<tr><td>${s.name}</td><td>₹${s.price}</td></tr>`)
      .join("")

    printWindow.document.write(`
      <html>
        <head>
          <title>Invoice ${invoice.invoiceNumber}</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { font-size: 24px; margin-bottom: 4px; }
            .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; }
            th { font-weight: 600; background: #f5f5f5; }
            .total-row { font-weight: bold; }
            .footer { margin-top: 40px; font-size: 14px; color: #666; }
          </style>
        </head>
        <body>
          <h1>Invoice</h1>
          <p class="meta">${invoice.invoiceNumber} | ${new Date(invoice.createdAt).toLocaleDateString()}</p>
          <p><strong>Customer:</strong> ${invoice.customerName}${invoice.customerPhone ? ` (${invoice.customerPhone})` : ""}</p>
          ${itemsRows ? `<table><thead><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>${itemsRows}</tbody></table>` : ""}
          ${servicesRows ? `<table><thead><tr><th>Service</th><th>Price</th></tr></thead><tbody>${servicesRows}</tbody></table>` : ""}
          ${invoice.labourCharges ? `<p><strong>Labour Charges:</strong> ₹${invoice.labourCharges}</p>` : ""}
          ${invoice.discount ? `<p><strong>Discount:</strong> -₹${invoice.discount}</p>` : ""}
          <p style="font-size: 20px; font-weight: bold;">Total: ₹${invoice.total}</p>
          ${invoice.notes ? `<p class="footer">${invoice.notes}</p>` : ""}
          <p class="footer">Generated by BolKeBill™</p>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  if (loading) {
    return (
      <div className="space-y-4 max-w-3xl mx-auto">
        <div className="flex items-center gap-4">
          <Skeleton className="h-9 w-9" />
          <div className="space-y-1">
            <Skeleton className="h-6 w-48" />
            <Skeleton className="h-4 w-32" />
          </div>
          <Skeleton className="h-6 w-16 ml-auto" />
        </div>
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Skeleton className="h-9 w-20" />
            <Skeleton className="h-9 w-20" />
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center gap-2">
              <Skeleton className="h-5 w-5" />
              <Skeleton className="h-4 w-24" />
              <Skeleton className="h-4 w-20 ml-auto" />
            </div>
            <Separator />
            <Skeleton className="h-4 w-16" />
            <Skeleton className="h-10 w-40" />
            <Skeleton className="h-4 w-12" />
            <div className="space-y-2">
              {Array.from({ length: 3 }).map((_, i) => (
                <div key={i} className="flex justify-between">
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-4 w-16" />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    )
  }

  if (!invoice) {
    return (
      <div className="text-center py-20">
        <FileText className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
        <h2 className="text-lg font-medium">Invoice not found</h2>
        <Button variant="outline" className="mt-4" asChild>
          <Link href="/dashboard/invoices">Back to Invoices</Link>
        </Button>
      </div>
    )
  }

  const statusColors: Record<string, string> = {
    draft: "bg-yellow-500/10 text-yellow-600 dark:text-yellow-400",
    sent: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    paid: "bg-green-500/10 text-green-600 dark:text-green-400",
    cancelled: "bg-red-500/10 text-red-600 dark:text-red-400",
  }

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" asChild>
            <Link href="/dashboard/invoices">
              <ArrowLeft className="h-4 w-4" />
            </Link>
          </Button>
          <div>
            <h1 className="text-xl font-bold">{invoice.invoiceNumber}</h1>
            <p className="text-sm text-muted-foreground">
              Created{" "}
              {new Date(invoice.createdAt).toLocaleDateString("en-IN", {
                day: "numeric",
                month: "long",
                year: "numeric",
              })}
            </p>
          </div>
        </div>
        <Badge variant="secondary" className={statusColors[invoice.status]}>
          {invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)}
        </Badge>
      </div>

      <div className="flex flex-wrap gap-2">
        {invoice.status === "draft" && (
          <>
            <Button size="sm" onClick={() => updateStatus("sent")}>
              <Send className="h-4 w-4" />
              Mark as Sent
            </Button>
            <Button size="sm" onClick={() => updateStatus("paid")}>
              <CheckCircle2 className="h-4 w-4" />
              Mark as Paid
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={() => updateStatus("cancelled")}
            >
              <XCircle className="h-4 w-4" />
              Cancel
            </Button>
          </>
        )}
        {invoice.status === "sent" && (
          <Button size="sm" onClick={() => updateStatus("paid")}>
            <CheckCircle2 className="h-4 w-4" />
            Mark as Paid
          </Button>
        )}
        <Button size="sm" variant="outline" onClick={handleDownload}>
          <Download className="h-4 w-4" />
          PDF
        </Button>
        <Button size="sm" variant="outline" onClick={handleWhatsApp}>
          <MessageSquare className="h-4 w-4" />
          WhatsApp
        </Button>
        {invoice.customerEmail && (
          <Button size="sm" variant="outline" onClick={handleSendEmail}>
            <Mail className="h-4 w-4" />
            Send Email
          </Button>
        )}
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Invoice Details</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-muted-foreground">Customer</p>
              <p className="font-medium">{invoice.customerName}</p>
              {invoice.customerPhone && (
                <p className="text-muted-foreground">{invoice.customerPhone}</p>
              )}
              {invoice.customerEmail && (
                <p className="text-muted-foreground">{invoice.customerEmail}</p>
              )}
            </div>
            <div className="text-right">
              <p className="text-muted-foreground">Source</p>
              <Badge variant="outline" className="mt-1">
                {invoice.source === "voice" ? "Voice" : "Manual"}
              </Badge>
            </div>
          </div>

          <Separator />

          {invoice.items.length > 0 && (
            <div>
              <h3 className="text-sm font-medium mb-3">Items</h3>
              <div className="overflow-x-auto border rounded">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-muted/50">
                      <th className="text-left p-3 font-medium text-muted-foreground">
                        Item
                      </th>
                      <th className="text-right p-3 font-medium text-muted-foreground">
                        Qty
                      </th>
                      <th className="text-right p-3 font-medium text-muted-foreground">
                        Rate
                      </th>
                      <th className="text-right p-3 font-medium text-muted-foreground">
                        Amount
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {invoice.items.map((item, i) => (
                      <tr key={i} className="border-t">
                        <td className="p-3">{item.name}</td>
                        <td className="p-3 text-right">{item.quantity}</td>
                        <td className="p-3 text-right">
                          ₹{item.price.toLocaleString("en-IN")}
                        </td>
                        <td className="p-3 text-right font-medium">
                          ₹{item.total.toLocaleString("en-IN")}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {invoice.services.length > 0 && (
            <div>
              <h3 className="text-sm font-medium mb-3">Services</h3>
              <div className="overflow-x-auto border rounded">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-muted/50">
                      <th className="text-left p-3 font-medium text-muted-foreground">
                        Service
                      </th>
                      <th className="text-right p-3 font-medium text-muted-foreground">
                        Amount
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {invoice.services.map((s, i) => (
                      <tr key={i} className="border-t">
                        <td className="p-3">{s.name}</td>
                        <td className="p-3 text-right font-medium">
                          ₹{s.price.toLocaleString("en-IN")}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          <Separator />

          <div className="space-y-1 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Subtotal</span>
              <span>₹{invoice.subtotal}</span>
            </div>
            {invoice.labourCharges > 0 && (
              <div className="flex justify-between">
                <span className="text-muted-foreground">Labour Charges</span>
                <span>₹{invoice.labourCharges}</span>
              </div>
            )}
            {invoice.discount > 0 && (
              <div className="flex justify-between">
                <span className="text-muted-foreground">Discount</span>
                <span className="text-destructive">-₹{invoice.discount}</span>
              </div>
            )}
            <div className="flex justify-between font-bold text-lg pt-2 border-t">
              <span>Total</span>
              <span>₹{invoice.total}</span>
            </div>
          </div>

          {invoice.notes && (
            <>
              <Separator />
              <div>
                <p className="text-sm text-muted-foreground">Notes</p>
                <p className="text-sm mt-1">{invoice.notes}</p>
              </div>
            </>
          )}

          {invoice.rawTranscript && (
            <>
              <Separator />
              <div>
                <p className="text-sm text-muted-foreground">
                  Original Voice Transcript
                </p>
                <p className="text-sm mt-1 italic">
                  &ldquo;{invoice.rawTranscript}&rdquo;
                </p>
              </div>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
