"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { toast } from "sonner"
import { CheckCircle2, MessageSquare, Download } from "lucide-react"
import { jsPDF } from "jspdf"

interface ActionInvoice {
  _id: string
  invoiceNumber: string
  customerName: string
  customerPhone?: string
  customerEmail?: string
  customerAddress?: string
  items: Array<{
    name: string
    quantity: number
    price: number
    total?: number
  }>
  services: Array<{ name: string; price: number }>
  subtotal: number
  tax?: number
  discount?: number
  labourCharges?: number
  total: number
  status: string
  notes?: string
  createdAt?: string
}

interface InvoiceActionsProps {
  invoice: ActionInvoice
  onStatusChange?: () => void
}

interface BusinessData {
  name: string
  email: string
  phone: string
  address: string
  gstin?: string
}

function formatDate(dateStr?: string) {
  if (!dateStr) return ""
  return new Date(dateStr).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })
}

function formatCurrency(n: number) {
  return `₹${n.toLocaleString("en-IN")}`
}

export function InvoiceActions({ invoice, onStatusChange }: InvoiceActionsProps) {
  const [business, setBusiness] = useState<BusinessData | null>(null)

  useEffect(() => {
    fetch("/api/business")
      .then((r) => r.json())
      .then((data) => {
        if (!data.error) setBusiness(data)
      })
      .catch(() => {})
  }, [])

  async function markAsPaid() {
    try {
      const res = await fetch(`/api/invoices/${invoice._id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "paid" }),
      })
      if (!res.ok) throw new Error("Failed to update")
      toast.success("Invoice marked as paid")
      onStatusChange?.()
    } catch {
      toast.error("Failed to update invoice")
    }
  }

  function getStatusBadge(status: string) {
    const colors: Record<string, string> = {
      paid: "#059669",
      sent: "#2563eb",
      draft: "#d97706",
      cancelled: "#dc2626",
    }
    return colors[status] || "#6b7280"
  }

  async function handleWhatsApp() {
    const message = [
      `Invoice: ${invoice.invoiceNumber}`,
      `Customer: ${invoice.customerName}`,
      "",
      ...invoice.items.map(
        (i) => `${i.name} x${i.quantity} = ${formatCurrency(i.total || i.quantity * i.price)}`,
      ),
      ...invoice.services.map((s) => `${s.name} = ${formatCurrency(s.price)}`),
      invoice.labourCharges ? `Labour: ${formatCurrency(invoice.labourCharges)}` : "",
      invoice.discount ? `Discount: -${formatCurrency(invoice.discount)}` : "",
      "",
      `Total: ${formatCurrency(invoice.total)}`,
      invoice.notes ? `\nNotes: ${invoice.notes}` : "",
      "",
      `Generated by ${business?.name || "HisaabAI"}`,
    ]
      .filter(Boolean)
      .join("\n")

    try {
      const doc = new jsPDF({ unit: "mm", format: "a4" })
      const pw = doc.internal.pageSize.getWidth()
      const ph = doc.internal.pageSize.getHeight()
      const ml = 20
      const mr = 20
      const cw = pw - ml - mr
      let y = 20
      const lineH = 6

      // --- Header: Business Details ---
      if (business) {
        doc.setFontSize(18)
        doc.setFont("helvetica", "bold")
        doc.text(business.name, ml, y)
        y += 7

        doc.setFontSize(9)
        doc.setFont("helvetica", "normal")
        doc.setTextColor(100)
        if (business.address) {
          doc.text(business.address, ml, y)
          y += 5
        }
        doc.text(`${business.email} | ${business.phone}`, ml, y)
        y += 5
        if (business.gstin) {
          doc.text(`GSTIN: ${business.gstin}`, ml, y)
          y += 5
        }
        doc.setTextColor(0)
      } else {
        doc.setFontSize(18)
        doc.setFont("helvetica", "bold")
        doc.text("INVOICE", pw / 2, y, { align: "center" })
        y += 7
      }

      // Separator line
      y += 3
      doc.setDrawColor(220)
      doc.setLineWidth(0.5)
      doc.line(ml, y, pw - mr, y)
      y += 8

      // --- Invoice Title Row ---
      doc.setFontSize(10)
      doc.setFont("helvetica", "bold")
      doc.text("INVOICE", ml, y)
      doc.setFont("helvetica", "normal")
      doc.text(`#${invoice.invoiceNumber}`, pw / 2, y)
      doc.text(formatDate(invoice.createdAt), pw - mr, y, { align: "right" })
      y += 5
      doc.setFontSize(8)
      doc.setTextColor(getStatusBadge(invoice.status))
      doc.text(invoice.status.toUpperCase(), ml, y)
      doc.setTextColor(0)

      y += 10

      // --- Billing Details ---
      const billCol = cw / 2
      doc.setFontSize(9)
      doc.setFont("helvetica", "bold")
      doc.text("Bill To", ml, y)
      doc.setFont("helvetica", "normal")
      y += 5
      doc.setFontSize(10)
      doc.text(invoice.customerName, ml, y)
      y += 5
      if (invoice.customerPhone) {
        doc.setFontSize(9)
        doc.setTextColor(100)
        doc.text(invoice.customerPhone, ml, y)
        y += 4
      }
      if (invoice.customerEmail) {
        doc.text(invoice.customerEmail, ml, y)
        y += 4
      }
      doc.setTextColor(0)

      // Reset y for items section
      y = Math.max(y + 5, 75)

      // --- Items Table Header ---
      if (invoice.items.length > 0) {
        doc.setDrawColor(200)
        doc.setFillColor(245, 245, 245)
        doc.rect(ml, y - 4, cw, 7, "F")
        doc.setFontSize(9)
        doc.setFont("helvetica", "bold")
        const cols = [
          { x: ml + 3, align: "left" as const, label: "Item" },
          { x: ml + cw - 80, align: "left" as const, label: "Qty" },
          { x: ml + cw - 50, align: "right" as const, label: "Rate" },
          { x: ml + cw - 3, align: "right" as const, label: "Amount" },
        ]
        cols.forEach((c) => doc.text(c.label, c.x, y, { align: c.align }))
        y += 7
        doc.setFont("helvetica", "normal")

        for (const item of invoice.items) {
          if (y > ph - 40) {
            doc.addPage()
            y = 20
          }
          const amount = item.total || item.quantity * item.price
          doc.setFontSize(9)
          doc.text(item.name, ml + 3, y)
          doc.text(String(item.quantity), ml + cw - 80, y)
          doc.text(formatCurrency(item.price), ml + cw - 50, y, { align: "right" })
          doc.setFont("helvetica", "bold")
          doc.text(formatCurrency(amount), ml + cw - 3, y, { align: "right" })
          doc.setFont("helvetica", "normal")
          y += 6
        }
        y += 3
      }

      // --- Services ---
      if (invoice.services.length > 0) {
        doc.setDrawColor(200)
        doc.setFillColor(245, 245, 245)
        doc.rect(ml, y - 4, cw, 7, "F")
        doc.setFontSize(9)
        doc.setFont("helvetica", "bold")
        doc.text("Service", ml + 3, y)
        doc.text("Amount", ml + cw - 3, y, { align: "right" })
        y += 7
        doc.setFont("helvetica", "normal")

        for (const s of invoice.services) {
          if (y > ph - 40) {
            doc.addPage()
            y = 20
          }
          doc.text(s.name, ml + 3, y)
          doc.setFont("helvetica", "bold")
          doc.text(formatCurrency(s.price), ml + cw - 3, y, { align: "right" })
          doc.setFont("helvetica", "normal")
          y += 6
        }
        y += 3
      }

      // --- Totals ---
      doc.setDrawColor(200)
      doc.line(ml, y, pw - mr, y)
      y += 5

      const totalX = ml + cw - 60
      const totalValX = ml + cw - 3

      function addTotalLine(label: string, value: string, bold = false, large = false) {
        doc.setFont("helvetica", bold ? "bold" : "normal")
        doc.setFontSize(large ? 12 : 9)
        doc.text(label, totalX, y)
        doc.text(value, totalValX, y, { align: "right" })
        y += large ? 8 : 6
      }

      addTotalLine("Subtotal", formatCurrency(invoice.subtotal))
      if (invoice.labourCharges) {
        addTotalLine("Labour Charges", formatCurrency(invoice.labourCharges))
      }
      if (invoice.discount) {
        addTotalLine("Discount", `-${formatCurrency(invoice.discount)}`)
      }

      doc.setDrawColor(100)
      doc.line(totalX, y, ml + cw, y)
      y += 3
      addTotalLine("Total", formatCurrency(invoice.total), true, true)

      // --- Notes ---
      if (invoice.notes) {
        y += 5
        doc.setDrawColor(220)
        doc.line(ml, y, pw - mr, y)
        y += 5
        doc.setFont("helvetica", "bold")
        doc.setFontSize(9)
        doc.text("Notes:", ml, y)
        y += 5
        doc.setFont("helvetica", "normal")
        doc.setFontSize(9)
        doc.setTextColor(100)
        doc.text(invoice.notes, ml, y)
        doc.setTextColor(0)
      }

      // --- Footer ---
      doc.setDrawColor(220)
      doc.line(ml, ph - 15, pw - mr, ph - 15)
      doc.setFontSize(8)
      doc.setTextColor(150)
      const footerText = `Generated by ${business?.name || "HisaabAI"}`
      doc.text(footerText, pw / 2, ph - 10, { align: "center" })
      doc.setTextColor(0)

      const pdfBlob = doc.output("blob")
      const pdfFile = new File(
        [pdfBlob],
        `Invoice_${invoice.invoiceNumber}.pdf`,
        { type: "application/pdf" },
      )

      const shareData: ShareData = {
        files: [pdfFile],
        text: message,
        title: `Invoice ${invoice.invoiceNumber}`,
      }

      if (navigator.canShare && navigator.canShare(shareData)) {
        await navigator.share(shareData)
      } else {
        const url = `https://wa.me/${invoice.customerPhone || "91"}?text=${encodeURIComponent(message)}`
        window.open(url, "_blank")
      }
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        const url = `https://wa.me/${invoice.customerPhone || "91"}?text=${encodeURIComponent(message)}`
        window.open(url, "_blank")
      }
    }
  }

  function handleDownload() {
    const biz = business || { name: "HisaabAI", email: "", phone: "", address: "", gstin: "" }

    const itemsRows = invoice.items
      .map(
        (i) =>
          `<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${i.name}</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${i.quantity}</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${i.price.toLocaleString("en-IN")}</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:600">${(i.total || i.quantity * i.price).toLocaleString("en-IN")}</td></tr>`,
      )
      .join("")

    const servicesRows = invoice.services
      .map(
        (s) =>
          `<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${s.name}</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:600">${s.price.toLocaleString("en-IN")}</td></tr>`,
      )
      .join("")

    const printWindow = window.open("", "_blank")
    if (!printWindow) return

    const statusColor = getStatusBadge(invoice.status)

    printWindow.document.write(`
      <html>
        <head>
          <title>Invoice ${invoice.invoiceNumber}</title>
          <style>
            @page { margin: 15mm; }
            * { box-sizing: border-box; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
              color: #1f2937;
              margin: 0;
              padding: 0;
              line-height: 1.5;
            }
            .invoice-container {
              max-width: 800px;
              margin: 0 auto;
            }
            .header {
              display: flex;
              justify-content: space-between;
              align-items: flex-start;
              padding-bottom: 20px;
              border-bottom: 2px solid #e5e7eb;
              margin-bottom: 24px;
            }
            .business-info h1 {
              font-size: 22px;
              font-weight: 700;
              margin: 0 0 4px 0;
              color: #111827;
            }
            .business-info p {
              margin: 2px 0;
              font-size: 12px;
              color: #6b7280;
            }
            .invoice-meta {
              text-align: right;
            }
            .invoice-meta h2 {
              font-size: 20px;
              font-weight: 700;
              margin: 0 0 4px 0;
              color: #111827;
            }
            .invoice-meta p {
              margin: 2px 0;
              font-size: 12px;
              color: #6b7280;
            }
            .status-badge {
              display: inline-block;
              padding: 3px 10px;
              border-radius: 0;
              font-size: 11px;
              font-weight: 600;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              color: #fff;
              background: ${statusColor};
              margin-top: 6px;
            }
            .billing-section {
              margin-bottom: 24px;
            }
            .billing-section h3 {
              font-size: 12px;
              font-weight: 600;
              color: #6b7280;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              margin: 0 0 8px 0;
            }
            .billing-section p {
              margin: 2px 0;
              font-size: 14px;
            }
            .billing-section .name {
              font-weight: 600;
              font-size: 15px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 20px 0;
              font-size: 13px;
            }
            thead th {
              background: #f9fafb;
              padding: 10px 12px;
              text-align: left;
              font-weight: 600;
              font-size: 12px;
              color: #6b7280;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              border-bottom: 2px solid #e5e7eb;
            }
            thead th:last-child { text-align: right; }
            tbody td { padding: 10px 12px; border-bottom: 1px solid #f3f4f6; }
            tbody td:last-child { text-align: right; font-weight: 600; }
            tbody tr:last-child td { border-bottom: 2px solid #e5e7eb; }
            .totals { margin-left: auto; width: 280px; }
            .totals table { margin: 0; }
            .totals td { padding: 6px 0; border: none; font-size: 13px; }
            .totals td:last-child { text-align: right; }
            .totals .grand-total td {
              font-weight: 700;
              font-size: 16px;
              padding-top: 10px;
              border-top: 2px solid #111827;
            }
            .notes-section {
              margin-top: 32px;
              padding-top: 16px;
              border-top: 1px solid #e5e7eb;
            }
            .notes-section h4 {
              font-size: 12px;
              font-weight: 600;
              color: #6b7280;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              margin: 0 0 6px 0;
            }
            .notes-section p {
              font-size: 13px;
              color: #6b7280;
              margin: 0;
            }
            .footer {
              margin-top: 40px;
              padding-top: 12px;
              border-top: 1px solid #e5e7eb;
              text-align: center;
              font-size: 11px;
              color: #9ca3af;
            }
            @media print {
              body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            }
          </style>
        </head>
        <body>
          <div class="invoice-container">

            <div class="header">
              <div class="business-info">
                <h1>${biz.name || "HisaabAI"}</h1>
                ${biz.address ? `<p>${biz.address}</p>` : ""}
                <p>${biz.email}${biz.phone ? ` | ${biz.phone}` : ""}</p>
                ${biz.gstin ? `<p>GSTIN: ${biz.gstin}</p>` : ""}
              </div>
              <div class="invoice-meta">
                <h2>INVOICE</h2>
                <p>#${invoice.invoiceNumber}</p>
                <p>${formatDate(invoice.createdAt)}</p>
                <div class="status-badge">${invoice.status}</div>
              </div>
            </div>

            <div class="billing-section">
              <h3>Bill To</h3>
              <p class="name">${invoice.customerName}</p>
              ${invoice.customerPhone ? `<p>${invoice.customerPhone}</p>` : ""}
              ${invoice.customerEmail ? `<p>${invoice.customerEmail}</p>` : ""}
            </div>

            ${invoice.items.length > 0 ? `
            <table>
              <thead>
                <tr>
                  <th style="width:50%">Item</th>
                  <th style="width:12%">Qty</th>
                  <th style="width:18%">Rate</th>
                  <th style="width:20%">Amount</th>
                </tr>
              </thead>
              <tbody>
                ${itemsRows}
              </tbody>
            </table>
            ` : ""}

            ${invoice.services.length > 0 ? `
            <table>
              <thead>
                <tr>
                  <th style="width:70%">Service</th>
                  <th style="width:30%">Amount</th>
                </tr>
              </thead>
              <tbody>
                ${servicesRows}
              </tbody>
            </table>
            ` : ""}

            <div class="totals">
              <table>
                <tr><td>Subtotal</td><td>${formatCurrency(invoice.subtotal)}</td></tr>
                ${invoice.labourCharges ? `<tr><td>Labour Charges</td><td>${formatCurrency(invoice.labourCharges)}</td></tr>` : ""}
                ${invoice.discount ? `<tr><td>Discount</td><td>-${formatCurrency(invoice.discount)}</td></tr>` : ""}
                <tr class="grand-total"><td>Total</td><td>${formatCurrency(invoice.total)}</td></tr>
              </table>
            </div>

            ${invoice.notes ? `
            <div class="notes-section">
              <h4>Notes</h4>
              <p>${invoice.notes}</p>
            </div>
            ` : ""}

            <div class="footer">
              Generated by ${biz.name || "HisaabAI"}
            </div>

          </div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  if (invoice.status === "paid") {
    return (
      <div className="flex flex-wrap gap-2">
        <Button size="sm" variant="outline" onClick={handleWhatsApp}>
          <MessageSquare className="h-4 w-4" />
          WhatsApp
        </Button>
        <Button size="sm" variant="outline" onClick={handleDownload}>
          <Download className="h-4 w-4" />
          PDF
        </Button>
      </div>
    )
  }

  return (
    <div className="flex flex-wrap gap-2">
      <Button size="sm" onClick={markAsPaid}>
        <CheckCircle2 className="h-4 w-4" />
        Mark as Paid
      </Button>
      <Button size="sm" variant="outline" onClick={handleWhatsApp}>
        <MessageSquare className="h-4 w-4" />
        WhatsApp
      </Button>
      <Button size="sm" variant="outline" onClick={handleDownload}>
        <Download className="h-4 w-4" />
        PDF
      </Button>
    </div>
  )
}
